### ISSUE TITLE
Add a glossary for templates variables

### ISSUE THREAD

**Issue by perrette** [ISI-MIP/isipedia-text-generator#1]
Define the variables that go in the [template files](https://github.com/ISI-MIP/isipedia-text-generator/blob/master/templates). For example:

- land_tc_rel_ov_md_1c : relative change in land exposed at 1C temperature (can be 2C etc...)
    - generic form: `{land}_tc_{rel}_ov_md_{1}c`
        - {land}: land or pop
        - {rel} : rel or abs or empty (no underscore)  ??
        - {1} : 0, 1, 2, 3, 4

or maybe it is better to give examples:
- land_tc_rel_ov_md_1c : relative change in land exposed at 1C temperature 
- land_tc_rel_ov_md_2c : same for 2C (0C to 4C)
- pop_tc_rel_ov_md_1c : same for population

**Comment by perrette** [comment]
The variable names will likely change so no need to do something too detailed. Maybe even better to wait a couple more days.

**Comment by BarbaraTempl** [comment]
Will @perrette change the variable names or who? And why? I am looking forward to having the glossary for variable names in the templates, would make my editing work easier:)

**Comment by perrette** [comment]
For now basically you have variables like:
- `land_tc_rel_ov_md_2c` : `land` or `pop`, `tc` for temperature change, `rel` for relative or `abs` for absolute or nothing for raw variable, and `2c` for 2-degree warming
`ov` and `md` mean overall and median (over all models), but forget about these because all variables refer to median, besides:
- `maximum_land_tc_rel_ov_md_2c` which is the `maximum` (or `minimum`) over all climate and impact models -- so actually `ov_md` there is a mistake ... first thing could be to just remove `ov_md` everywhere. Then there is
- `land_rcp26_abs_far_future` where rcp26 or rcp60 is the scenario, and `far_future` or `today` the time frame (2081-2100 and 2001-2020, respectively). We could add more time frames, like near-future (2041-2060). 

In more details:
- `pop` is % of population exposed to droughts or else
- `land` is % of land affected by droughts or else
 
Relative `rel` means `(var - var0) / var0 * 100` in %, where `var0` is the average over a reference period (I think 1986-2005), and absolute means `var - var0` (also in %, confusingly, because pop and land base variables are also in %).

And you have a few more extras like country name etc...

You can access world variables as `world.<var name>` where <var name> is the variable just described.

**Comment by perrette** [comment]
I want not only to change the variable names but to define a grammar. See discussion on issue #2

**Comment by JulianHunt4** [comment]
Hi Mahé, thanks for writing the Glossary. It looks great! 
Sorry for not being able to work on in before.
I have seen that you have made a substantial advance in creating textgenerator templete for all indicators. 
I could not understand how it works. 
Please let me know how I can assist you.

**Comment by perrette** [comment]
Yes it works fine in ~ 200 lines. It can be improved for clarity. Basically I generate a list of `variables` in the data cube sense, i.e. each variable corresponds to one json file, e.g. `land-area-affected-by-drought-relative-changes_ISIMIP-projections_versus-temperature-change`. I just loop around these variables and do the job for each (load json, calculate numbers for various degrees of warming or scenario/time slice), give it the appropriate name, e.g. `land_tc_ov_md_2c` and eventually process the templates. For now there is nothing I need assistance for, but please keep posted, I will try to write issues for things that need to be done. Let's talk on a per-task basis. For now there is none I can think of as far as the country reports are concerned.
