### ISSUE TITLE
world and country templates

### ISSUE THREAD

**Issue by perrette** [ISI-MIP/isipedia-text-generator#12]
Maybe we do not need to have two files if only some parts changes. Jinja2 templating system with inheritance mechanism could be a neat way to solve this.

@BarbaraTempl 
Please try to edit country and world reports at the same time, or do not let them diverge too much from each other, so that I have a chance to simplify.

**Comment by JulianHunt4** [comment]
True.

**Comment by perrette** [comment]
My suggestion is to use a smarter templating system where everything that is common should be written once and for all, and "imported" or inserted where we need it (e.g. in every report). As a basic principle, it is important to remove redundancy otherwise the maintainance is too heavy.

Let's take a look at [jinja2's template inheritance system](https://jinja.palletsprojects.com/en/2.10.x/templates/#template-inheritance) to understand the philosophy.

_Originally posted by @perrette in https://github.com/ISI-MIP/isipedia-text-generator/issues/13#issuecomment-539517365_

**Comment by perrette** [comment]
Of course there is a balance to strike between a system with no redundancy and readability/ease of use/flexibility for authors.

**Comment by perrette** [comment]
For now a working system of hierarchical templates. We might come back to it later.
