### ISSUE TITLE
Test run

### ISSUE THREAD

**Issue by rgieseke** [ISI-MIP/isipedia-text-generator#19]
is it possible to run this with the local test data only? There are some hard-coded values in isipedia/config.json

**Comment by perrette** [comment]
The `text_generator.py` script runs with test-data by default (reads json files there and update each directory with appropriate markdown files taken from the templates/ directory).
Try it with `--help` flag to see other options.

**Comment by perrette** [comment]
Right help was buggy thanks for the fix !

**Comment by perrette** [comment]
I am surprised it is read at all. I think this is due to an import of the `isipedia` module that is not really required at this stage. Let me look at it.
