### ISSUE TITLE
Add logics to templates

### ISSUE THREAD

**Issue by perrette** [ISI-MIP/isipedia-text-generator#2]
Right now the templates are made from a dictionary (see issue #1) of variables.
But the dictionary is build on logics... (combinations of {land, pop} x {rel, abs, ''} x {timeslice, warming} x scenarios+timeslice or warming level.
It would be more elegant to make the logic more visible.

Logic can be added in jinja2 with [filters](https://jinja.palletsprojects.com/en/2.10.x/api/#writing-filters) `| action`, such as `land_rcp60_rel | max` or `land_rcp60_rel | median`, but this needs to be thought through carefully @matthiasmengel.

Alternatively, and preferentially, define new markdown commands to do exactly that. I think aiming for markdown commands is more appropriate since some markdown commands already exist, e.g. 
`(ranking-value: land-area-affected-by-drought-relative-changes_ISIMIP-projections_versus-temperature-change_{country.code} value: position temperature:2)`

**Comment by JulianHunt4** [comment]
Let me see if I understand what you mean: 
1) You are proposing to stop working on the textgenerator as we have been developing.
2) You propose that the indicators should be written directly in a Markdown file, where the variables are indicated within the text. For example, as in (ranking-value: land-area-affected-by-drought-relative-changes_ISIMIP-projections_versus-temperature-change_{country.code} value: position temperature:2)
3) We would then provide the guidelines for filling up the Markdown file. 

This is an genius idea! It would make our job much simpler.
We could even try to get the sectoral coordinators to do it, if we provide enough documentation. If the sectoral coordinators are not capable of doing it, we can do it for them. 

Shall we do it this way instead?

**Comment by perrette** [comment]
That is more or less the way I rewrote it. This does not mean the code is not developed further. Please try to understand how the current `textgenerator.py` is working. 

https://github.com/ISI-MIP/isipedia-text-generator/issues/1#issuecomment-539513014

**Comment by perrette** [comment]
The commit above (bc2ac62) shows the impact of replacing simple dict variable with logics, in the form of a markdown command. 

`{rank_pop_tc_rel_2c}`

becomes 

`(ranking-value: population-exposed-to-river-flood-relative-changes_ISIMIP-projections_versus-temperature-change_PAK value: position temperature:2)`

It is long : ) -- but flexible.
Alternatively, one could have shorter logics using jinja2, such as

`{rank(pop_temp_rel, 2)}` 

or whatever. This example shows it is not so simple. Anyways, I'd say that issue is not prioritary and for now a glossary of pre-computed variables is just fine. I close for now.

**Comment by perrette** [comment]
@matthiasmengel

**Comment by matthiasmengel** [comment]
Nice idea! A good glossary that you already started probably also does the job for now. The very long version can be quite confusing in sentences with many numbers I guess.
