### ISSUE TITLE
rounding variables

### ISSUE THREAD

**Issue by perrette** [ISI-MIP/isipedia-text-generator#7]
This is only an issue in the sense that it is not done yet.

On a side note, @BarbaraTempl, it just occurred to me that you can control the rounding [from the template](https://docs.python.org/3/library/string.html#format-examples), adding `:format` after the variable name in the curly brackets `{}`. For instance `{some_variable:.0f}` for no decimals (rounded) or  `{some_variable:.2f}` for two decimals. Of course if any single variable should be rounded, let me do that for you the source code and transform the numbers in integers from the beginning.

Better not doing anything for now as we might go for a new templating option anyway.

**Comment by BarbaraTempl** [comment]
Will play around with this as soon as i can run the templates with the test data.

**Comment by perrette** [comment]
You should be able to run it any time by just cloning this repo.

**Comment by perrette** [comment]
Then `python textgenerator.py`
