### ISSUE TITLE
Check variables in report templates

### ISSUE THREAD

**Issue by perrette** [ISI-MIP/isipedia-text-generator#8]
Check variable naming and correctness of use, e.g. from the drought.md template:

> land area affected by droughts is projected to increase by a factor of {land_tc_rel_ov_md_2c}

and later:

> land area affected by droughts is projected to change by a factor of {land_tc_rel_ov_md_2c_times}

or 

> this factor is projected to reach {land_rcp60_far_future_times} for the land area affected to droughts (to {land_rcp60_far_future_times}%)

In one case the suffix `_times` is used, in the other not, whereas the intended meaning is the same. Moreover, looking at the code, `times` is simply a division by 100 +1 compared to original variable, which does not make much sense to me for a variable other than relative `rel`. 

Is there any explanation for that @JulianHunt4?

**Comment by perrette** [comment]
My understanding is that 
- the first template quote above is not correct, and should include `_times` whenever `factor is meant`
- Whenever relative quantities (`rel`) are considered (such as `land_tc_rel_ov_md_2c`), the variable means a % increase compared to the reference period, but one might want to express that as a factor -- OK -- but that is not correct for other variables (like abs), where `_times` was defined as well
- a source of confusion is that the "raw" variable is already expressed as a %, even when not expressed in a relative term ! Nonetheless, `_times` should not exist for variables other than `rel`.

**Comment by perrette** [comment]
I modified templates accordingly (see commit referenced above)

**Comment by JulianHunt4** [comment]
You are right. It was a mistake. Thanks for fixing it.
